### ISSUE TITLE
Miniscript Descriptor Sarvanan Mani jan 13-24

### ISSUE THREAD

**Issue by VirdiJatin** [Bitshala/bitdevs#1]
Edited video link: 
https://drive.google.com/file/d/1j4LWP6nwSitBxtJblNUAv97JdxGOegMy/view?usp=drive_link 

Timelines:
3:42 - what is Miniscript/ Bitcoin script?
10:11 - Example for spending condition 
12:36 - Limitations of Miniscript 
15:37 - Is Miniscript primary for bitcoin developers? How it impacts end user?
21:33 - How Miniscript magic works..
25:01 - what is a Bitcoin Wallet?
25:28 - How we send Bitcoin?
26:29 - Challenges with regular Wallet
32:45 - Descriptor + Miniscript 
37:37 - Demo
38:19 - What is PSBT?
40:13 - Example

**Comment by VirdiJatin** [comment]
@setusaurabh ping for description and @paperpsych for Thumbnail..

**Comment by paperpsych** [comment]
@setusaurabh @rajarshimaitra Will the theme of thumbnail include elements of BITDEVS? Since this was an offline talk, will that be conveyed in the title of the video and thumbnail or not?

**Comment by setusaurabh** [comment]
I think the theme could be similar to the meetup announcement posters but that this is already over as in no dates to go with it. Those posters used to convey that these events are offline from the imagery itself, so that would be great.

**Comment by setusaurabh** [comment]
hey @VirdiJatin lets start the description of each video with a description on how they can join this next week. It will be sort of anouncement like we have on our discord calendar invite. 
Post that description, we will describe the current video. It achieves an important goal which is to inform the viewers as to how can they join us in real time next time.

**Comment by VirdiJatin** [comment]
@paperpsych Reping for thumbnail..

**Comment by paperpsych** [comment]
Apologies for the delay. Please use this...

![BITDEVS - Saravanan Mani](https://github.com/Bitshala/bitdevs/assets/149538435/1d3bcb07-15b2-40f3-89d2-c481c625ede0)

[Drive link](https://drive.google.com/file/d/1DHaGJZ8_u96v3TgGLgWzGjAjz885_TaD/view?usp=drive_link)
